spring:
  application:
    name: questions-service
  data:
    mongodb:
      uri: mongodb+srv://serbantiurbe:gfKlzad6pSyYoVEA@interviewcompanionappcl.0dt0g6v.mongodb.net/?retryWrites=true&w=majority&appName=InterviewCompanionAppCluster
      database: questions
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/springboot-microservice-realm
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
          useInsecureTrustManager: true
logging:
  level:
    org:
      springframework:
        web: DEBUG
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
server:
  port: '8083'
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
management:
  tracing:
    sampling:
      probability: '1.0'
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
springdoc:
  swagger-ui:
    path: /swagger-ui.html
jwt:
  auth:
    converter:
      resource-id: microservice-auth
      principle-attribute: preferred_username